= 勤怠記録および記録操作 Web API

株式会社ベイクラフトの勤怠記録をするためのアプリケーションです。

本アプリケーションは２つのモジュールで構成されます。１つ目はSlackの呟きを受信してDBへ記録（Slackボット）、２つ目はDBに記録された勤怠記録を操作するためのWeb APIです。Slackボットモジュールのロジックは https://github.com/masuidrive/miyamoto[勤怠管理bot - みやもとさん] を参考にしています。そのため、記録される呟きの書式は一部改修した部分を除き同一です。

== Slackボットモジュールについて

=== 出勤記録

以下のようなメッセージに反応します。
----
モーニング, モ〜ニング, もーにんぐ, も〜にんぐ, おっは, おは, へろ, はろ, ヘロ, ハロ, hi, hello, morning, 出勤
----

メッセージには日時を指定することが可能です。日時を指定しない場合は現在日時で記録されます。
----
おはようございます 2020/1/29 9:00
おはようございます 1/29 9:00
おはようございます 1/29
おはようございます
----

=== 退勤記録

以下のようなメッセージに反応します。
----
バイ, バーイ, バ〜イ, バァイ, ばい, ばーい, ば〜い, ばぁい, おやすみ, おつ, おっー, さらば, お先, お疲, 帰, 乙, bye, night, cu, c u, cyou, c you, seeu, see u, seeyou, see you, 退勤, ごきげんよ, グッバイ, グバイ, さようなら
----

メッセージには日時を指定することが可能です。日時を指定しない場合は現在日時で記録されます。
----
お疲れ様でした 2020/1/29 17:30
お疲れ様でした 1/29 17:30
お疲れ様でした 1/29
お疲れ様でした
----

=== 休暇記録

以下のようなメッセージに反応します。
----
休, やすま, やすみ, やすむ, 休暇
----

メッセージには日時を指定することが可能です。日時を指定しない場合は現在日時で記録されます。
----
休み 2020/1/29 17:30
休み 1/29 17:30
休み 1/29
休み
----

また、シングルクォートで文字列を括ることでメモ情報を記録することができます。
----
休み 1/30 "ここがメモとして記録される"
休み "ここがメモとして記録される"
----

== 開発メモ

=== 環境構築

1. https://baykraft.slack.com にアクセス
2. 左側メニューの「アプリを追加する」を選択
3. 検索欄に「Hubot」と入力
4. Hubotをインストール

=== Herokuへの環境変数設定

[source,sh]
----
heroku config:set BOT_API_TOKEN="hubotのaccess_token"
----

=== Heroku上のPostgreSQLへのアクセス

[source,sh]
----
heroku pg:psql
----

=== Viewモジュールのコピー

time-recorder-viewリポジトリをビルドし、生成されたbuildフォルダをtemplatesフォルダとして
time-recorderへコピーする。
